"""Version information for the Spagraph package."""
__version__ = "0.1.0"
__author__ = "Spagraph contributors"
__email__ = ""
__description__ = "Spagraph: VAE + GAT pipeline for spatial transcriptomics deconvolution"
