"""Version information for the Spagraph package."""
__version__ = "0.1.0"
__author__ = "Your Name"
__email__ = "your.email@example.com"
__description__ = "Spagraph: VAE + GAT pipeline for spatial transcriptomics deconvolution"
